#!/usr/bin/env python3
"""ingest_fixture.py — the fixture acceptance gate for Pāṭala Benchmark v0.

Moves a candidate fixture through:
  CANDIDATE → schema validation → source resolution → leakage inspection
             → human check → BENCHMARK_ACCEPTED

Refuses to freeze weak fixtures (the reviewer's warning): anything generated by the same
method being evaluated is marked DERIVED_FROM_PRODUCT and excluded from that method's eval.

Run: cd benchmarks/v0 && python ../../machinelearning/research/ingest_fixture.py <fixture.json>
"""
from __future__ import annotations

import json
import os
import sys

SCHEMA_REQUIRED = ["fixture_id", "task_family", "task", "source_ids", "gold_version",
                   "authoring_method", "review_state", "allowed_training_use",
                   "split_class", "input", "expected"]
VALID_FAMILIES = ["PATALA-RETRIEVAL", "PATALA-EVIDENCE", "PATALA-STRUCTURE", "PATALA-FIDELITY"]
VALID_REVIEW = ["CANDIDATE", "SINGLE_EDITOR_GOLD", "DOUBLE_REVIEWED_GOLD", "ADJUDICATED_GOLD"]
VALID_SPLIT = ["EVALUATION_ONLY", "S0", "S1", "S2", "S3", "S4"]


def validate_schema(f: dict) -> list[str]:
    problems = []
    for k in SCHEMA_REQUIRED:
        if k not in f:
            problems.append(f"missing {k}")
    if f.get("task_family") not in VALID_FAMILIES:
        problems.append(f"bad task_family {f.get('task_family')}")
    if f.get("review_state") not in VALID_REVIEW:
        problems.append(f"bad review_state {f.get('review_state')}")
    if f.get("split_class") not in VALID_SPLIT:
        problems.append(f"bad split_class {f.get('split_class')}")
    if not isinstance(f.get("allowed_training_use"), bool):
        problems.append("allowed_training_use must be bool")
    return problems


def resolve_sources(f: dict) -> list[str]:
    """Check each source_id resolves to a real passage or is an explicitly-flagged artifact."""
    problems = []
    import glob
    store = "/root/projects/patala/data/published/ipvv"
    index_path = os.path.join(store, "index.json")
    known = set()
    if os.path.exists(index_path):
        idx = json.load(open(index_path))
        known = {p["id"] for p in idx["passages"]}
    for sid in f.get("source_ids", []):
        if sid.startswith("pt:passage:ipvv:chunk"):
            if sid not in known:
                problems.append(f"unresolved passage {sid}")
        elif sid.startswith("C1:"):
            c1f = f"/mnt/HC_Volume_106427611/sanskritree/translations/_stack/ipvv/c1/read/c1_{sid[3:]}.md"
            if not os.path.exists(c1f):
                problems.append(f"unresolved C1 {sid}")
        elif sid.startswith("l200:"):
            pass  # audit references are acceptable
        else:
            problems.append(f"unknown source_id form: {sid}")
    return problems


def leakage_inspect(f: dict) -> list[str]:
    """Anti-circularity: a fixture produced by method X cannot gold-evaluate X."""
    problems = []
    am = f.get("authoring_method", "")
    if am == "DERIVED_FROM_PRODUCT":
        problems.append("DERIVED_FROM_PRODUCT: cannot be independent gold for its generating method")
    return problems


def main():
    if len(sys.argv) < 2:
        print("usage: ingest_fixture.py <fixture.json>"); sys.exit(2)
    f = json.load(open(sys.argv[1]))
    fid = f.get("fixture_id", "?")
    probs = validate_schema(f) + resolve_sources(f) + leakage_inspect(f)
    if probs:
        print(f"❌ {fid} REJECTED:")
        for p in probs:
            print(f"   - {p}")
        sys.exit(1)
    # accepted: if it's gold, mark it
    rs = f.get("review_state", "CANDIDATE")
    print(f"✅ {fid} BENCHMARK_ACCEPTED (review_state={rs}, split={f.get('split_class')}, "
          f"train_use={f.get('allowed_training_use')})")
    if rs == "CANDIDATE":
        print("   NOTE: still CANDIDATE — needs a reviewer to sign to become gold.")


if __name__ == "__main__":
    main()
