// GET /api/corpus/state — the Agent 2 translation-state ledger (the corpus control plane).
//   ?work=kramasadbhava  → one work's full state + next action
//   (default)            → the whole ledger
//
// This is the machine-readable state that Agent 3 (the translation factory) consumes:
// per work, its source/translation/L0/proof/review state + NEXT_VALID_ACTION + eligibility.
// Generated by pipeline/corpus_state.py (Agent 2 owns state truth). Served READ-ONLY here;
// the site/agents never mutate it via the API — Agent 2 regenerates it from disk truth.

import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

const LEDGER_PATH = path.join(process.cwd(), "data/corpus/downloads/translation-state-ledger.json");

export async function GET(req: NextRequest) {
  const work = req.nextUrl.searchParams.get("work");

  let ledger;
  try {
    ledger = JSON.parse(fs.readFileSync(LEDGER_PATH, "utf-8"));
  } catch (e) {
    return NextResponse.json(
      { error: "ledger_unavailable", detail: "run pipeline/corpus_state.py to regenerate" },
      { status: 503 }
    );
  }

  const works = ledger.works || {};

  if (work) {
    const w = works[work];
    if (!w) return NextResponse.json({ error: "no_work", work }, { status: 404 });
    return NextResponse.json({ work, state: w });
  }

  return NextResponse.json({
    count: Object.keys(works).length,
    note: "Agent 2 translation-state ledger (corpus compiler / integrity layer). NEXT_VALID_ACTION is the control plane for Agent 3. Regenerate via pipeline/corpus_state.py.",
    works,
  });
}
