#!/usr/bin/env python3
"""pipeline/argument_worker.py — the ARGUMENT layer handler (model-derived, gated).

Per BUILDSTATUS (POST-C1 lane) + the patala doctrine:
  - ARGUMENT is a REAL argument reconstructed from a committed C1 claim, with the
    required structure: premises -> inference -> conclusion -> counterargument -> crux.
  - The argument TEXT is GENERATED by the MODEL (the generation engine:
    lib/gateway_exec.py -> deepseek-v4-flash via opencode-go) over the REAL
    committed C1 payload. Never hand-typed, never regex-built, never relabeled C1
    text (that was the honest gap the v1 DERIVED_FROM_C1_TEXT records fixed).
  - A deterministic ARGUMENT validator gates the commit: the object must be
    structurally complete (conclusion, premises, inference, counterargument, crux
    with an in-range load-bearing premise), status MACHINE_PROPOSED, derived by
    the model (gateway_exec), and resolve to a committed C1.
  - ENGINEERING_VALIDATED is a structural/engineering result, NOT a scholarly
    truth claim. The state ladder stays honest:
    MACHINE_PROPOSED -> ENGINEERING_VALIDATED -> SCHOLARLY_CORROBORATED ->
    INDEPENDENT_REVIEWED. The gate can justify the first transition only.

Mirrors pipeline/theme_worker.py: generator + validator handlers so the autonomy
controller can wire make_argument_handlers() the same way.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "pipeline"))
sys.path.insert(0, str(REPO / "machinelearning/research"))
sys.path.insert(0, "/root/fuck-off/lib")  # the PROVEN generation engine (gateway_exec)

import object_registry as R  # noqa: E402

try:
    from gateway_exec import generate_json  # noqa: E402
    _GATEWAY = True
except Exception as _e:  # pragma: no cover
    _GATEWAY = False
    _GATEWAY_ERR = str(_e)

DERIVED_BY = "model (gateway_exec)"

PROMPT_SYSTEM = (
    "You are a Sanskrit philologist reconstructing a rigorous scholarly argument from a claim. "
    "Produce a REAL argument: premises that LOGICALLY SUPPORT a conclusion, with an explicit "
    "inference, a serious counterargument, and the crux (the load-bearing premise). Derive every "
    "sentence strictly from the provided claim text. Do not add external claims. Output ONLY JSON, "
    "no reasoning, no markdown. "
    'Format exactly: {"conclusion": str, "premises": [{"text": str}], "inference": str, '
    '"counterargument": str, "crux": {"load_bearing_premise": int, "why": str}} '
    "where load_bearing_premise is the 1-based index of the premise the conclusion depends on most."
)


def committed_c1_ids() -> list[str]:
    """Current (non-superseded) C1 object ids — the derivational floor."""
    reg = R._load("C1")
    out = []
    for oid, vs in reg["objects"].items():
        if any(not v.get("superseded") for v in vs):
            out.append(oid)
    return sorted(out)


def canonical_input_hash(c1_oid: str) -> str:
    """The canonical ARGUMENT input hash: sha256 of the REAL current C1 payload.

    Semantics: same committed C1 -> same hash -> is_committed() idempotent. (The
    earlier non-canonical records hashed their own payload, so idempotency broke.)
    """
    cur = R.current("C1", c1_oid)
    if not cur:
        raise KeyError(f"no current C1: {c1_oid}")
    return hashlib.sha256(
        json.dumps(cur["payload"], sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()


def model_derive_argument(c1_oid: str, max_attempts: int = 5) -> dict | None:
    """Have the MODEL derive the argument from the real committed C1 payload.

    Returns the parsed model JSON (conclusion / premises / inference / counterargument /
    crux) or None if the model is unavailable or returns junk after retries.
    The gateway occasionally returns empty content; retry with backoff before
    giving up (an honest abstention beats a fabricated argument).
    """
    if not _GATEWAY:
        return None
    cur = R.current("C1", c1_oid)
    if not cur:
        return None
    c = cur["payload"].get("c1") or {}
    user = (
        f"CLAIM summary: {c.get('summary','')}\n"
        f"CLAIM function: {c.get('function','')}\n"
        f"CLAIM explanation: {c.get('explanation','')}\n"
        f"CLAIM boundary: {c.get('boundary','')}\n"
        f"CLAIM key_terms: {c.get('key_terms')}\n"
        f"CLAIM uncertain: {c.get('uncertain')}"
    )
    last = None
    for attempt in range(max_attempts):
        try:
            res = generate_json(PROMPT_SYSTEM, user, max_tokens=1500, timeout=120)
            if (res.get("conclusion") and isinstance(res.get("premises"), list)
                    and res.get("premises") and res.get("inference")
                    and res.get("counterargument") and isinstance(res.get("crux"), dict)):
                return res
            last = f"structurally incomplete response: {str(res)[:200]}"
        except Exception as e:  # network / parse / timeout
            last = str(e)
        time.sleep(2 * (attempt + 1))
    if last:
        _last_error[0] = f"{c1_oid}: {last}"
    return None


_last_error: list[str] = [""]


def last_error() -> str:
    return _last_error[0]


def assemble_argument_payload(c1_oid: str, model_res: dict) -> dict:
    """Build the registry payload from the model's JSON + the real C1 fidelity fields."""
    cur = R.current("C1", c1_oid)
    if not cur:
        raise KeyError(f"no current C1: {c1_oid}")
    c = cur["payload"].get("c1") or {}
    premises = [
        {"id": f"{c1_oid}__P{i + 1}", "text": str(p.get("text", "")).strip(),
         "role": "supporting_premise"}
        for i, p in enumerate(model_res.get("premises") or [])
        if str(p.get("text", "")).strip()
    ]
    try:
        lbp = int(model_res.get("crux", {}).get("load_bearing_premise"))
    except (TypeError, ValueError):
        lbp = 0
    crux = {
        "load_bearing_premise": lbp,
        "why": str(model_res.get("crux", {}).get("why", "")).strip(),
    }
    payload = {
        "argument": {
            "argument_id": f"arg:{c1_oid}",
            "conclusion": {"text": str(model_res.get("conclusion", "")).strip(),
                           "source": c1_oid},
            "premises": premises,
            "inference": str(model_res.get("inference", "")).strip(),
            "counterargument": str(model_res.get("counterargument", "")).strip(),
            "crux": crux,
            "key_terms": list(c.get("key_terms") or []),
            "uncertain": list(c.get("uncertain") or []),
            "boundary": str(c.get("boundary") or "").strip(),
        },
        "argument_status": "MACHINE_PROPOSED",
        "derived_by": DERIVED_BY,
    }
    return payload


def argument_validator(layer: str, proposal: dict) -> tuple[bool, str]:
    """Deterministic ARGUMENT gate.

    - argument_status MACHINE_PROPOSED (never claims a higher state by construction)
    - argument_id present and matching the source C1
    - conclusion.text present, source resolves to the C1
    - premises non-empty, each with id + text
    - inference present
    - counterargument present
    - crux present with an IN-RANGE load-bearing premise index (1-based) + why
    - derived_by == "model (gateway_exec)"  (anti-theatre: never hand-fed)
    - input_refs[0] resolves to a committed C1 in the registry
    - fidelity: key_terms / uncertain / boundary carried from the C1 payload
    """
    if proposal.get("argument_status") != "MACHINE_PROPOSED":
        return False, f"argument_status:{proposal.get('argument_status', 'MISSING')}"
    if proposal.get("derived_by") != DERIVED_BY:
        return False, f"derived_by:{proposal.get('derived_by', 'MISSING')} (must be model (gateway_exec))"
    arg = proposal.get("argument", {})
    c1_oid = proposal.get("input_refs", [""])[0] or arg.get("conclusion", {}).get("source", "")
    if not c1_oid:
        return False, "no input_refs / conclusion.source (cannot resolve to C1)"
    if arg.get("argument_id") != f"arg:{c1_oid}":
        return False, f"argument_id:{arg.get('argument_id','MISSING')} != arg:{c1_oid}"
    conclusion = arg.get("conclusion") or {}
    if not str(conclusion.get("text", "")).strip():
        return False, "conclusion.text empty"
    if conclusion.get("source") != c1_oid:
        return False, f"conclusion.source:{conclusion.get('source')} != {c1_oid}"
    premises = arg.get("premises") or []
    if not premises:
        return False, "no premises"
    for i, p in enumerate(premises):
        if not p.get("id") or not str(p.get("text", "")).strip():
            return False, f"premise {i} missing id or text"
    if not str(arg.get("inference", "")).strip():
        return False, "inference empty"
    if not str(arg.get("counterargument", "")).strip():
        return False, "counterargument empty"
    crux = arg.get("crux") or {}
    try:
        lbp = int(crux.get("load_bearing_premise"))
    except (TypeError, ValueError):
        return False, f"crux.load_bearing_premise not an int: {crux.get('load_bearing_premise')!r}"
    if not (1 <= lbp <= len(premises)):
        return False, f"crux.load_bearing_premise {lbp} out of range 1..{len(premises)}"
    if not str(crux.get("why", "")).strip():
        return False, "crux.why empty"
    # fidelity: the argument carries the C1's key_terms / uncertain / boundary
    cur = R.current("C1", c1_oid)
    if not cur:
        return False, f"input_ref C1 unresolved: {c1_oid}"
    c = cur["payload"].get("c1") or {}
    if list(arg.get("key_terms") or []) != list(c.get("key_terms") or []):
        return False, "key_terms not carried from C1 (fidelity)"
    if list(arg.get("uncertain") or []) != list(c.get("uncertain") or []):
        return False, "uncertain not carried from C1 (fidelity)"
    if str(arg.get("boundary") or "").strip() != str(c.get("boundary") or "").strip():
        return False, "boundary not carried from C1 (fidelity)"
    return True, ""


def argument_generator(layer: str, batch: list[dict]) -> list[dict]:
    """Model-derive ONE ARGUMENT proposal per committed C1 in the batch.

    Returns proposals with object_id / input_hash / argument / argument_status /
    derived_by / input_refs. Caller (worker) gates + commits each.
    """
    out = []
    for b in batch:
        c1_oid = b.get("object_id", "")
        if not R.current("C1", c1_oid):
            continue
        res = model_derive_argument(c1_oid)
        if res is None:
            print(f"  ✗ {c1_oid}: model derivation FAILED — not fabricating ({last_error()})")
            continue
        payload = assemble_argument_payload(c1_oid, res)
        out.append({
            "object_id": f"{c1_oid}__arg",
            "input_hash": canonical_input_hash(c1_oid),
            "input_refs": [c1_oid],
            "argument": payload["argument"],
            "argument_status": payload["argument_status"],
            "derived_by": payload["derived_by"],
        })
    return out


def make_argument_handlers() -> dict:
    return {"generator": argument_generator, "validator": argument_validator}


if __name__ == "__main__":
    print("gateway available:", _GATEWAY)
    print("committed C1s:", committed_c1_ids())
