// Generated by pipeline/compile_published.py — do not edit by hand.
// Kramasadbhāva 1.1–1.25 published auditable translation objects (Level 1).
import type { PublishedTranslation } from "../translation";

export const kramasadbhava_1_25: Record<string, PublishedTranslation> = {
  "pt:passage:kramasadbhava:1.1": {
  "passage_id": "pt:passage:kramasadbhava:1.1",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.1:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.1:1",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:2",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:3",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:4",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "(?)"
    },
    {
      "id": "pt:srcspan:krs:1.1:5",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "kā"
    },
    {
      "id": "pt:srcspan:krs:1.1:6",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "ama"
    },
    {
      "id": "pt:srcspan:krs:1.1:7",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:8",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:9",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:10",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:11",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.1:12",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "(?)"
    },
    {
      "id": "pt:srcspan:krs:1.1:13",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "hā"
    },
    {
      "id": "pt:srcspan:krs:1.1:14",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "yata"
    },
    {
      "id": "pt:srcspan:krs:1.1:15",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "kṣyayanti"
    },
    {
      "id": "pt:srcspan:krs:1.1:16",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "pivanti"
    },
    {
      "id": "pt:srcspan:krs:1.1:17",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "ca"
    },
    {
      "id": "pt:srcspan:krs:1.1:18",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "aśarīrāḥ"
    },
    {
      "id": "pt:srcspan:krs:1.1:19",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "śarīrasthāḥ"
    },
    {
      "id": "pt:srcspan:krs:1.1:20",
      "passage_id": "pt:passage:kramasadbhava:1.1",
      "text": "kālyārādhanatatparāḥ"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.1:v1"
  }
},
  "pt:passage:kramasadbhava:1.2": {
  "passage_id": "pt:passage:kramasadbhava:1.2",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.2:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.2:1",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "tasmiṃ"
    },
    {
      "id": "pt:srcspan:krs:1.2:2",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "cakre"
    },
    {
      "id": "pt:srcspan:krs:1.2:3",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "mahāghore"
    },
    {
      "id": "pt:srcspan:krs:1.2:4",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "mahāmātṛbhiḥ"
    },
    {
      "id": "pt:srcspan:krs:1.2:5",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "saṃkule"
    },
    {
      "id": "pt:srcspan:krs:1.2:6",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "svavimarśadaśanibhā"
    },
    {
      "id": "pt:srcspan:krs:1.2:7",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.2:8",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.2:9",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.2:10",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.2:11",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.2:12",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.2:13",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.2:14",
      "passage_id": "pt:passage:kramasadbhava:1.2",
      "text": "*(?)"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.2:v1"
  }
},
  "pt:passage:kramasadbhava:1.3": {
  "passage_id": "pt:passage:kramasadbhava:1.3",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.3:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.3:1",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "kālī"
    },
    {
      "id": "pt:srcspan:krs:1.3:2",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "tu"
    },
    {
      "id": "pt:srcspan:krs:1.3:3",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "bhairavārūḍhā"
    },
    {
      "id": "pt:srcspan:krs:1.3:4",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "mahākālakalāśinī"
    },
    {
      "id": "pt:srcspan:krs:1.3:5",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "vyomarūpā"
    },
    {
      "id": "pt:srcspan:krs:1.3:6",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "anantākhyā"
    },
    {
      "id": "pt:srcspan:krs:1.3:7",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "aṣṭamūrtidharā"
    },
    {
      "id": "pt:srcspan:krs:1.3:8",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "text": "śivā"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [
    {
      "id": "pt:decision:krs:1.3:LEX:1",
      "passage_id": "pt:passage:kramasadbhava:1.3",
      "translation_version_id": "pt:translation:kramasadbhava:1.3:v1",
      "source_span_ids": [
        "pt:srcspan:krs:1.3:1"
      ],
      "target_span_ids": [],
      "type": "LEXICAL",
      "claim": "devadeveśi — sense unresolved",
      "surface_rendering": "",
      "alternatives": [],
      "status": "OPEN",
      "evidence_state": "evidence_missing",
      "editorial_status": "proposed",
      "reason": "Known crux (devadeveśi) at 1.3; no research yet. Honest marker, not a resolution.",
      "method": "pipeline",
      "evidence": [],
      "review_events": [],
      "origin": "machine",
      "created_at": "2026-08-10",
      "created_by": "compiler"
    }
  ],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.3:v1"
  }
},
  "pt:passage:kramasadbhava:1.4": {
  "passage_id": "pt:passage:kramasadbhava:1.4",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.4:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.4:1",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "pañcāśadrudrakhacitā"
    },
    {
      "id": "pt:srcspan:krs:1.4:2",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "catuḥṣaṣṭistu"
    },
    {
      "id": "pt:srcspan:krs:1.4:3",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "bhāvitā"
    },
    {
      "id": "pt:srcspan:krs:1.4:4",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.4:5",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "*"
    },
    {
      "id": "pt:srcspan:krs:1.4:6",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "(?)"
    },
    {
      "id": "pt:srcspan:krs:1.4:7",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "brahmā"
    },
    {
      "id": "pt:srcspan:krs:1.4:8",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "tathā"
    },
    {
      "id": "pt:srcspan:krs:1.4:9",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "viṣṇu"
    },
    {
      "id": "pt:srcspan:krs:1.4:10",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "rudra"
    },
    {
      "id": "pt:srcspan:krs:1.4:11",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "īśvara"
    },
    {
      "id": "pt:srcspan:krs:1.4:12",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "eva"
    },
    {
      "id": "pt:srcspan:krs:1.4:13",
      "passage_id": "pt:passage:kramasadbhava:1.4",
      "text": "ca"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.4:v1"
  }
},
  "pt:passage:kramasadbhava:1.5": {
  "passage_id": "pt:passage:kramasadbhava:1.5",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.5:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.5:1",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "sadāśivo"
    },
    {
      "id": "pt:srcspan:krs:1.5:2",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "mahādevo"
    },
    {
      "id": "pt:srcspan:krs:1.5:3",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "bhairavaścaiva"
    },
    {
      "id": "pt:srcspan:krs:1.5:4",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "saptamaḥ"
    },
    {
      "id": "pt:srcspan:krs:1.5:5",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "pretatve"
    },
    {
      "id": "pt:srcspan:krs:1.5:6",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "saṃsthitā"
    },
    {
      "id": "pt:srcspan:krs:1.5:7",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "nityaṃ"
    },
    {
      "id": "pt:srcspan:krs:1.5:8",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "tasyā"
    },
    {
      "id": "pt:srcspan:krs:1.5:9",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "devyāstu"
    },
    {
      "id": "pt:srcspan:krs:1.5:10",
      "passage_id": "pt:passage:kramasadbhava:1.5",
      "text": "sarvataḥ"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.5:v1"
  }
},
  "pt:passage:kramasadbhava:1.6": {
  "passage_id": "pt:passage:kramasadbhava:1.6",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.6:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.6:1",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "teṣāṃ"
    },
    {
      "id": "pt:srcspan:krs:1.6:2",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "madhye"
    },
    {
      "id": "pt:srcspan:krs:1.6:3",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "mahābhīmo"
    },
    {
      "id": "pt:srcspan:krs:1.6:4",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "bhairavo"
    },
    {
      "id": "pt:srcspan:krs:1.6:5",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "vai"
    },
    {
      "id": "pt:srcspan:krs:1.6:6",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "nirāmayaḥ"
    },
    {
      "id": "pt:srcspan:krs:1.6:7",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "suśrūṣo"
    },
    {
      "id": "pt:srcspan:krs:1.6:8",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "gaṅgado"
    },
    {
      "id": "pt:srcspan:krs:1.6:9",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "bhūtvā"
    },
    {
      "id": "pt:srcspan:krs:1.6:10",
      "passage_id": "pt:passage:kramasadbhava:1.6",
      "text": "tasyārādhanatatparaḥ"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.6:v1"
  }
},
  "pt:passage:kramasadbhava:1.7": {
  "passage_id": "pt:passage:kramasadbhava:1.7",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.7:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.7:1",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "pādau"
    },
    {
      "id": "pt:srcspan:krs:1.7:2",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "jagrāha"
    },
    {
      "id": "pt:srcspan:krs:1.7:3",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "tasyā"
    },
    {
      "id": "pt:srcspan:krs:1.7:4",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "vai"
    },
    {
      "id": "pt:srcspan:krs:1.7:5",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "stutipūrvamidaṃ"
    },
    {
      "id": "pt:srcspan:krs:1.7:6",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "vacaḥ"
    },
    {
      "id": "pt:srcspan:krs:1.7:7",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "abravīt"
    },
    {
      "id": "pt:srcspan:krs:1.7:8",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "tu"
    },
    {
      "id": "pt:srcspan:krs:1.7:9",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "samāsena"
    },
    {
      "id": "pt:srcspan:krs:1.7:10",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "bhairavo"
    },
    {
      "id": "pt:srcspan:krs:1.7:11",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "bhairavīṃ"
    },
    {
      "id": "pt:srcspan:krs:1.7:12",
      "passage_id": "pt:passage:kramasadbhava:1.7",
      "text": "tataḥ"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.7:v1"
  }
},
  "pt:passage:kramasadbhava:1.8": {
  "passage_id": "pt:passage:kramasadbhava:1.8",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[the maṅgala:] oṃ, homage-to-you, O-goddess-of-gods, O-great-Kālī, homage-be-to-you; homage-be [to you], O-supreme-bliss, [and]-the-...(*?) [X: \"nirānande\" — the-bliss-less?], homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.8:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.8:1",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "śrībhairava"
    },
    {
      "id": "pt:srcspan:krs:1.8:2",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "uvāca"
    },
    {
      "id": "pt:srcspan:krs:1.8:3",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "ooṃ"
    },
    {
      "id": "pt:srcspan:krs:1.8:4",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "namaste"
    },
    {
      "id": "pt:srcspan:krs:1.8:5",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "devadeveśi"
    },
    {
      "id": "pt:srcspan:krs:1.8:6",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "mahākāli"
    },
    {
      "id": "pt:srcspan:krs:1.8:7",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.8:8",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.8:9",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.8:10",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "paramānande"
    },
    {
      "id": "pt:srcspan:krs:1.8:11",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "nirānande"
    },
    {
      "id": "pt:srcspan:krs:1.8:12",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.8:13",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.8:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.8:v1",
      "text": "\"[the maṅgala:] oṃ, homage-to-you, O-goddess-of-gods, O-great-Kālī, homage-be-to-you; homage-be [to you], O-supreme-bliss, [and]-the-...(*?) [X: \"nirānande\" — the-bliss-less?], homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.8:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.8:1",
        "pt:srcspan:krs:1.8:2",
        "pt:srcspan:krs:1.8:3",
        "pt:srcspan:krs:1.8:4",
        "pt:srcspan:krs:1.8:5",
        "pt:srcspan:krs:1.8:6",
        "pt:srcspan:krs:1.8:7",
        "pt:srcspan:krs:1.8:8",
        "pt:srcspan:krs:1.8:9",
        "pt:srcspan:krs:1.8:10",
        "pt:srcspan:krs:1.8:11",
        "pt:srcspan:krs:1.8:12",
        "pt:srcspan:krs:1.8:13"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.8:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [
    {
      "id": "pt:decision:krs:1.8:LEX:1",
      "passage_id": "pt:passage:kramasadbhava:1.8",
      "translation_version_id": "pt:translation:kramasadbhava:1.8:v1",
      "source_span_ids": [
        "pt:srcspan:krs:1.8:1"
      ],
      "target_span_ids": [],
      "type": "LEXICAL",
      "claim": "nirānande — sense unresolved",
      "surface_rendering": "\"[the maṅgala:] oṃ, homage-to-you, O-goddess-of-gods, O-great-Kālī, homage-be-to-you; homage-be [to you], O-supreme-bliss, [and]-the-...(*?) [X: \"nirānande\" — the-bliss-less?], homage-be-to-you:\"",
      "alternatives": [],
      "status": "OPEN",
      "evidence_state": "evidence_missing",
      "editorial_status": "proposed",
      "reason": "Known crux (nirānande) at 1.8; no research yet. Honest marker, not a resolution.",
      "method": "pipeline",
      "evidence": [],
      "review_events": [],
      "origin": "machine",
      "created_at": "2026-08-10",
      "created_by": "compiler"
    }
  ],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.8:v1"
  }
},
  "pt:passage:kramasadbhava:1.9": {
  "passage_id": "pt:passage:kramasadbhava:1.9",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-homage, O-eternal, [and]-to-you, O-non-eternal, homage-always, O-great-souled; homage, O-kula-mistress, O-Kaula-mistress, O-knowledge-powered (vijñāna-vibhave), homage:\"",
  "version_id": "pt:translation:kramasadbhava:1.9:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.9:1",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "namo"
    },
    {
      "id": "pt:srcspan:krs:1.9:2",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "nitye"
    },
    {
      "id": "pt:srcspan:krs:1.9:3",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "tvanitye"
    },
    {
      "id": "pt:srcspan:krs:1.9:4",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "ca"
    },
    {
      "id": "pt:srcspan:krs:1.9:5",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "namaḥ"
    },
    {
      "id": "pt:srcspan:krs:1.9:6",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "sadā"
    },
    {
      "id": "pt:srcspan:krs:1.9:7",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "mahātmike"
    },
    {
      "id": "pt:srcspan:krs:1.9:8",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "namaḥ"
    },
    {
      "id": "pt:srcspan:krs:1.9:9",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "kuleśi"
    },
    {
      "id": "pt:srcspan:krs:1.9:10",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "kauleśi"
    },
    {
      "id": "pt:srcspan:krs:1.9:11",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "vijñānavibhave"
    },
    {
      "id": "pt:srcspan:krs:1.9:12",
      "passage_id": "pt:passage:kramasadbhava:1.9",
      "text": "namaḥ"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.9:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.9:v1",
      "text": "\"[and]-homage, O-eternal, [and]-to-you, O-non-eternal, homage-always, O-great-souled; homage, O-kula-mistress, O-Kaula-mistress, O-knowledge-powered (vijñāna-vibhave), homage:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.9:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.9:1",
        "pt:srcspan:krs:1.9:2",
        "pt:srcspan:krs:1.9:3",
        "pt:srcspan:krs:1.9:4",
        "pt:srcspan:krs:1.9:5",
        "pt:srcspan:krs:1.9:6",
        "pt:srcspan:krs:1.9:7",
        "pt:srcspan:krs:1.9:8",
        "pt:srcspan:krs:1.9:9",
        "pt:srcspan:krs:1.9:10",
        "pt:srcspan:krs:1.9:11",
        "pt:srcspan:krs:1.9:12"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.9:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.9:v1"
  }
},
  "pt:passage:kramasadbhava:1.10": {
  "passage_id": "pt:passage:kramasadbhava:1.10",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-homage, O-the-effecting-of-the-...-the-...(*?) [X: \"kṛtānta-durdānta-kālasya-karaṇodyate\" — the time of the end], [and]-homage-to-the-māyā-and-the-rest-powered (māyādi-vaibhavyai), O-world-gaping (viśvajṛmbhe), protect-me:\"",
  "version_id": "pt:translation:kramasadbhava:1.10:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.10:1",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "namaḥ"
    },
    {
      "id": "pt:srcspan:krs:1.10:2",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "kṛtāntadurdāntakālasya"
    },
    {
      "id": "pt:srcspan:krs:1.10:3",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "karaṇodyate"
    },
    {
      "id": "pt:srcspan:krs:1.10:4",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "namo"
    },
    {
      "id": "pt:srcspan:krs:1.10:5",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "māyādivaibhavyai"
    },
    {
      "id": "pt:srcspan:krs:1.10:6",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "viśvajṛmbhe"
    },
    {
      "id": "pt:srcspan:krs:1.10:7",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "rakṣa"
    },
    {
      "id": "pt:srcspan:krs:1.10:8",
      "passage_id": "pt:passage:kramasadbhava:1.10",
      "text": "me"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.10:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.10:v1",
      "text": "\"[and]-homage, O-the-effecting-of-the-...-the-...(*?) [X: \"kṛtānta-durdānta-kālasya-karaṇodyate\" — the time of the end], [and]-homage-to-the-māyā-and-the-rest-powered (māyādi-vaibhavyai), O-world-gaping (viśvajṛmbhe), protect-me:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.10:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.10:1",
        "pt:srcspan:krs:1.10:2",
        "pt:srcspan:krs:1.10:3",
        "pt:srcspan:krs:1.10:4",
        "pt:srcspan:krs:1.10:5",
        "pt:srcspan:krs:1.10:6",
        "pt:srcspan:krs:1.10:7",
        "pt:srcspan:krs:1.10:8"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.10:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.10:v1"
  }
},
  "pt:passage:kramasadbhava:1.11": {
  "passage_id": "pt:passage:kramasadbhava:1.11",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-homage, [and]-the-...(*?), [and]-of-that-very, [and]-the-root (*?), O-capable-in-the-dissolution (saṃharaṇa-kṣame), homage-be-to-you, O-great-fierce (mahāraudri), O-calm-formed (saumya-rūpe), homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.11:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.11:1",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "namo"
    },
    {
      "id": "pt:srcspan:krs:1.11:2",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "harthāntu"
    },
    {
      "id": "pt:srcspan:krs:1.11:3",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "tasyaiva"
    },
    {
      "id": "pt:srcspan:krs:1.11:4",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "mūlaṃ"
    },
    {
      "id": "pt:srcspan:krs:1.11:5",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "(?)"
    },
    {
      "id": "pt:srcspan:krs:1.11:6",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "saṃharaṇe"
    },
    {
      "id": "pt:srcspan:krs:1.11:7",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "kṣame"
    },
    {
      "id": "pt:srcspan:krs:1.11:8",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.11:9",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.11:10",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "mahāraudri"
    },
    {
      "id": "pt:srcspan:krs:1.11:11",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "saumyarūpe"
    },
    {
      "id": "pt:srcspan:krs:1.11:12",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.11:13",
      "passage_id": "pt:passage:kramasadbhava:1.11",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.11:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.11:v1",
      "text": "\"[and]-homage, [and]-the-...(*?), [and]-of-that-very, [and]-the-root (*?), O-capable-in-the-dissolution (saṃharaṇa-kṣame), homage-be-to-you, O-great-fierce (mahāraudri), O-calm-formed (saumya-rūpe), homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.11:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.11:1",
        "pt:srcspan:krs:1.11:2",
        "pt:srcspan:krs:1.11:3",
        "pt:srcspan:krs:1.11:4",
        "pt:srcspan:krs:1.11:5",
        "pt:srcspan:krs:1.11:6",
        "pt:srcspan:krs:1.11:7",
        "pt:srcspan:krs:1.11:8",
        "pt:srcspan:krs:1.11:9",
        "pt:srcspan:krs:1.11:10",
        "pt:srcspan:krs:1.11:11",
        "pt:srcspan:krs:1.11:12",
        "pt:srcspan:krs:1.11:13"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.11:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.11:v1"
  }
},
  "pt:passage:kramasadbhava:1.12": {
  "passage_id": "pt:passage:kramasadbhava:1.12",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-form-less, O-sound-less, O-womb, O-stationed-in-the-sixteenth-end (*?) [X: \"ṣoḍaśānte\" — the end-of-the-sixteen], [and]-O-stationed-in-the-will-formed-own-nature (icchā-rūpa-svabhāva-sthe), O-Bhairavī, homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.12:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.12:1",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "arūpe"
    },
    {
      "id": "pt:srcspan:krs:1.12:2",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "asvare"
    },
    {
      "id": "pt:srcspan:krs:1.12:3",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "garbhe"
    },
    {
      "id": "pt:srcspan:krs:1.12:4",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "ṣoḍaśānte"
    },
    {
      "id": "pt:srcspan:krs:1.12:5",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "vyavasthite"
    },
    {
      "id": "pt:srcspan:krs:1.12:6",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "icchārūpasvabhāvasthe"
    },
    {
      "id": "pt:srcspan:krs:1.12:7",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "bhairaveśi"
    },
    {
      "id": "pt:srcspan:krs:1.12:8",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.12:9",
      "passage_id": "pt:passage:kramasadbhava:1.12",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.12:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.12:v1",
      "text": "\"[and]-O-form-less, O-sound-less, O-womb, O-stationed-in-the-sixteenth-end (*?) [X: \"ṣoḍaśānte\" — the end-of-the-sixteen], [and]-O-stationed-in-the-will-formed-own-nature (icchā-rūpa-svabhāva-sthe), O-Bhairavī, homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.12:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.12:1",
        "pt:srcspan:krs:1.12:2",
        "pt:srcspan:krs:1.12:3",
        "pt:srcspan:krs:1.12:4",
        "pt:srcspan:krs:1.12:5",
        "pt:srcspan:krs:1.12:6",
        "pt:srcspan:krs:1.12:7",
        "pt:srcspan:krs:1.12:8",
        "pt:srcspan:krs:1.12:9"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.12:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.12:v1"
  }
},
  "pt:passage:kramasadbhava:1.13": {
  "passage_id": "pt:passage:kramasadbhava:1.13",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-worshipped-by-the-knowledge, O-great-knowledge, O-knowable-formed, homage-be-to-you; O-action-formed (kriyā-rūpe), O-great-formed, O-all-world-formed (viśva-rūpe), homage-be-to-you:\" \"[and]-O-the-cessation-end-of-the-being-and-non-being (*?), O-all-absence, homage-be-to-you; O-stationed-in-the-midst-of-the-bliss-step, O-the-end-of-the-appearance (*?), homage-be-to-you; O-the-womb-of-the-delight-step, indeed, O-pervasion-formed, homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.13:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.13:1",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "jñānopāsye"
    },
    {
      "id": "pt:srcspan:krs:1.13:2",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "mahājñāne"
    },
    {
      "id": "pt:srcspan:krs:1.13:3",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "jñeyarūpe"
    },
    {
      "id": "pt:srcspan:krs:1.13:4",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.13:5",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.13:6",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "kriyārūpe"
    },
    {
      "id": "pt:srcspan:krs:1.13:7",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "mahārūpe"
    },
    {
      "id": "pt:srcspan:krs:1.13:8",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "viśvarūpe"
    },
    {
      "id": "pt:srcspan:krs:1.13:9",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.13:10",
      "passage_id": "pt:passage:kramasadbhava:1.13",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.13:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.13:v1",
      "text": "\"[and]-O-worshipped-by-the-knowledge, O-great-knowledge, O-knowable-formed, homage-be-to-you; O-action-formed (kriyā-rūpe), O-great-formed, O-all-world-formed (viśva-rūpe), homage-be-to-you:\" \"[and]-O-the-cessation-end-of-the-being-and-non-being (*?), O-all-absence, homage-be-to-you; O-stationed-in-the-midst-of-the-bliss-step, O-the-end-of-the-appearance (*?), homage-be-to-you; O-the-womb-of-the-delight-step, indeed, O-pervasion-formed, homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.13:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.13:1",
        "pt:srcspan:krs:1.13:2",
        "pt:srcspan:krs:1.13:3",
        "pt:srcspan:krs:1.13:4",
        "pt:srcspan:krs:1.13:5",
        "pt:srcspan:krs:1.13:6",
        "pt:srcspan:krs:1.13:7",
        "pt:srcspan:krs:1.13:8",
        "pt:srcspan:krs:1.13:9",
        "pt:srcspan:krs:1.13:10"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.13:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.13:v1"
  }
},
  "pt:passage:kramasadbhava:1.14": {
  "passage_id": "pt:passage:kramasadbhava:1.14",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.14:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.14:1",
      "passage_id": "pt:passage:kramasadbhava:1.14",
      "text": "bhāvābhāvavirāmānte"
    },
    {
      "id": "pt:srcspan:krs:1.14:2",
      "passage_id": "pt:passage:kramasadbhava:1.14",
      "text": "sarvābhāve"
    },
    {
      "id": "pt:srcspan:krs:1.14:3",
      "passage_id": "pt:passage:kramasadbhava:1.14",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.14:4",
      "passage_id": "pt:passage:kramasadbhava:1.14",
      "text": "te"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.14:v1"
  }
},
  "pt:passage:kramasadbhava:1.15": {
  "passage_id": "pt:passage:kramasadbhava:1.15",
  "work_id": "pt:work:kramasadbhava",
  "text": "",
  "version_id": "pt:translation:kramasadbhava:1.15:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.15:1",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "ānandapadamadhyasthe"
    },
    {
      "id": "pt:srcspan:krs:1.15:2",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "ābhāsānte"
    },
    {
      "id": "pt:srcspan:krs:1.15:3",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.15:4",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.15:5",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "āhlādapadagarbhe"
    },
    {
      "id": "pt:srcspan:krs:1.15:6",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "tu"
    },
    {
      "id": "pt:srcspan:krs:1.15:7",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "vyāptirūpe"
    },
    {
      "id": "pt:srcspan:krs:1.15:8",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.15:9",
      "passage_id": "pt:passage:kramasadbhava:1.15",
      "text": "te"
    }
  ],
  "target_spans": [],
  "alignments": [],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.15:v1"
  }
},
  "pt:passage:kramasadbhava:1.16": {
  "passage_id": "pt:passage:kramasadbhava:1.16",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-stationed-in-the-step-of-the-visarga-end, O-all-mistress, homage-be-to-you; O-sound-formed (nāda-rūpe), O-great-sound, O-the-called-Sadākhyā, homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.16:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.16:1",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "visargāntapadāvasthe"
    },
    {
      "id": "pt:srcspan:krs:1.16:2",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "sarveśvari"
    },
    {
      "id": "pt:srcspan:krs:1.16:3",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.16:4",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.16:5",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "nādarūpe"
    },
    {
      "id": "pt:srcspan:krs:1.16:6",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "mahānāde"
    },
    {
      "id": "pt:srcspan:krs:1.16:7",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "sādākhyāyai"
    },
    {
      "id": "pt:srcspan:krs:1.16:8",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.16:9",
      "passage_id": "pt:passage:kramasadbhava:1.16",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.16:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.16:v1",
      "text": "\"[and]-O-stationed-in-the-step-of-the-visarga-end, O-all-mistress, homage-be-to-you; O-sound-formed (nāda-rūpe), O-great-sound, O-the-called-Sadākhyā, homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.16:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.16:1",
        "pt:srcspan:krs:1.16:2",
        "pt:srcspan:krs:1.16:3",
        "pt:srcspan:krs:1.16:4",
        "pt:srcspan:krs:1.16:5",
        "pt:srcspan:krs:1.16:6",
        "pt:srcspan:krs:1.16:7",
        "pt:srcspan:krs:1.16:8",
        "pt:srcspan:krs:1.16:9"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.16:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.16:v1"
  }
},
  "pt:passage:kramasadbhava:1.17": {
  "passage_id": "pt:passage:kramasadbhava:1.17",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-gone-to-the-drop's-own-nature (*?), O-the-called-rasa-drop (rasa-bindu), homage-be-to-you; O-power-formed (śakti-rūpe), indeed, O-body-stationed, O-all-state, homage-be-to-*:\"",
  "version_id": "pt:translation:kramasadbhava:1.17:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.17:1",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "bindusvabhāvage"
    },
    {
      "id": "pt:srcspan:krs:1.17:2",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "rasabindvākhye"
    },
    {
      "id": "pt:srcspan:krs:1.17:3",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "ca"
    },
    {
      "id": "pt:srcspan:krs:1.17:4",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.17:5",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.17:6",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "śaktirūpe"
    },
    {
      "id": "pt:srcspan:krs:1.17:7",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "tu"
    },
    {
      "id": "pt:srcspan:krs:1.17:8",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "dehasthe"
    },
    {
      "id": "pt:srcspan:krs:1.17:9",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "sarvāvasthe"
    },
    {
      "id": "pt:srcspan:krs:1.17:10",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.17:11",
      "passage_id": "pt:passage:kramasadbhava:1.17",
      "text": "*"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.17:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.17:v1",
      "text": "\"[and]-O-gone-to-the-drop's-own-nature (*?), O-the-called-rasa-drop (rasa-bindu), homage-be-to-you; O-power-formed (śakti-rūpe), indeed, O-body-stationed, O-all-state, homage-be-to-*:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.17:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.17:1",
        "pt:srcspan:krs:1.17:2",
        "pt:srcspan:krs:1.17:3",
        "pt:srcspan:krs:1.17:4",
        "pt:srcspan:krs:1.17:5",
        "pt:srcspan:krs:1.17:6",
        "pt:srcspan:krs:1.17:7",
        "pt:srcspan:krs:1.17:8",
        "pt:srcspan:krs:1.17:9",
        "pt:srcspan:krs:1.17:10",
        "pt:srcspan:krs:1.17:11"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.17:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.17:v1"
  }
},
  "pt:passage:kramasadbhava:1.18": {
  "passage_id": "pt:passage:kramasadbhava:1.18",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-unmanifest, O-stationed-in-the-manifest-being, O-pervasion-formed, homage-be-to-you; O-Śiva-formed, O-great-peace, O-beyond-the-peace (śāntātīte), homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.18:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.18:1",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "avyakte"
    },
    {
      "id": "pt:srcspan:krs:1.18:2",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "vyaktibhāvasthe"
    },
    {
      "id": "pt:srcspan:krs:1.18:3",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "vyāptirūpe"
    },
    {
      "id": "pt:srcspan:krs:1.18:4",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.18:5",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.18:6",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "śivarūpe"
    },
    {
      "id": "pt:srcspan:krs:1.18:7",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "mahāśānte"
    },
    {
      "id": "pt:srcspan:krs:1.18:8",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "śāntātīte"
    },
    {
      "id": "pt:srcspan:krs:1.18:9",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.18:10",
      "passage_id": "pt:passage:kramasadbhava:1.18",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.18:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.18:v1",
      "text": "\"[and]-O-unmanifest, O-stationed-in-the-manifest-being, O-pervasion-formed, homage-be-to-you; O-Śiva-formed, O-great-peace, O-beyond-the-peace (śāntātīte), homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.18:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.18:1",
        "pt:srcspan:krs:1.18:2",
        "pt:srcspan:krs:1.18:3",
        "pt:srcspan:krs:1.18:4",
        "pt:srcspan:krs:1.18:5",
        "pt:srcspan:krs:1.18:6",
        "pt:srcspan:krs:1.18:7",
        "pt:srcspan:krs:1.18:8",
        "pt:srcspan:krs:1.18:9",
        "pt:srcspan:krs:1.18:10"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.18:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.18:v1"
  }
},
  "pt:passage:kramasadbhava:1.19": {
  "passage_id": "pt:passage:kramasadbhava:1.19",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-in-the-twelfth-end (dvādaśānte), [and]-in-the-ninth-end, [and]-in-the-thirty-sixth-end, homage-be-to-you; O-stationed-in-the-pistil-of-the-heart-lotus, O-flame-formed (jvālā-rūpe), homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.19:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.19:1",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "dvādaśānte"
    },
    {
      "id": "pt:srcspan:krs:1.19:2",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "navānte"
    },
    {
      "id": "pt:srcspan:krs:1.19:3",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "ca"
    },
    {
      "id": "pt:srcspan:krs:1.19:4",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "ṣaṭtriṃśānte"
    },
    {
      "id": "pt:srcspan:krs:1.19:5",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.19:6",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.19:7",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "hṛtpadmakarṇikāntasthe"
    },
    {
      "id": "pt:srcspan:krs:1.19:8",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "jvālārūpe"
    },
    {
      "id": "pt:srcspan:krs:1.19:9",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.19:10",
      "passage_id": "pt:passage:kramasadbhava:1.19",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.19:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.19:v1",
      "text": "\"[and]-O-in-the-twelfth-end (dvādaśānte), [and]-in-the-ninth-end, [and]-in-the-thirty-sixth-end, homage-be-to-you; O-stationed-in-the-pistil-of-the-heart-lotus, O-flame-formed (jvālā-rūpe), homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.19:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.19:1",
        "pt:srcspan:krs:1.19:2",
        "pt:srcspan:krs:1.19:3",
        "pt:srcspan:krs:1.19:4",
        "pt:srcspan:krs:1.19:5",
        "pt:srcspan:krs:1.19:6",
        "pt:srcspan:krs:1.19:7",
        "pt:srcspan:krs:1.19:8",
        "pt:srcspan:krs:1.19:9",
        "pt:srcspan:krs:1.19:10"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.19:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.19:v1"
  }
},
  "pt:passage:kramasadbhava:1.20": {
  "passage_id": "pt:passage:kramasadbhava:1.20",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-always-stationed-in-the-throat-region, O-hunger-remover (kṣudhā-harti), homage-be-to-you; O-stationed-in-the-palate, O-great-Kālī, O-all-devouring (sarva-bhakṣye), homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.20:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.20:1",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "kaṇṭhadeśe"
    },
    {
      "id": "pt:srcspan:krs:1.20:2",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "tu"
    },
    {
      "id": "pt:srcspan:krs:1.20:3",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "nityasthe"
    },
    {
      "id": "pt:srcspan:krs:1.20:4",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "kṣudhāharti"
    },
    {
      "id": "pt:srcspan:krs:1.20:5",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.20:6",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.20:7",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "tālusthe"
    },
    {
      "id": "pt:srcspan:krs:1.20:8",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "tu"
    },
    {
      "id": "pt:srcspan:krs:1.20:9",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "mahākāli"
    },
    {
      "id": "pt:srcspan:krs:1.20:10",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "sarvabhakṣye"
    },
    {
      "id": "pt:srcspan:krs:1.20:11",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.20:12",
      "passage_id": "pt:passage:kramasadbhava:1.20",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.20:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.20:v1",
      "text": "\"[and]-O-always-stationed-in-the-throat-region, O-hunger-remover (kṣudhā-harti), homage-be-to-you; O-stationed-in-the-palate, O-great-Kālī, O-all-devouring (sarva-bhakṣye), homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.20:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.20:1",
        "pt:srcspan:krs:1.20:2",
        "pt:srcspan:krs:1.20:3",
        "pt:srcspan:krs:1.20:4",
        "pt:srcspan:krs:1.20:5",
        "pt:srcspan:krs:1.20:6",
        "pt:srcspan:krs:1.20:7",
        "pt:srcspan:krs:1.20:8",
        "pt:srcspan:krs:1.20:9",
        "pt:srcspan:krs:1.20:10",
        "pt:srcspan:krs:1.20:11",
        "pt:srcspan:krs:1.20:12"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.20:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.20:v1"
  }
},
  "pt:passage:kramasadbhava:1.21": {
  "passage_id": "pt:passage:kramasadbhava:1.21",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-stationed-in-the-midst-of-the-two-bows (kodaṇḍa-dvaya), [and]-at-the-drop's-end, homage-be-to-you; O-stationed-at-the-Brahmā's-door, O-Kālī, O-object-formed (vastu-rūpe), homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.21:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.21:1",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "kodaṇḍadvayamadhyasthe"
    },
    {
      "id": "pt:srcspan:krs:1.21:2",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "bindvante"
    },
    {
      "id": "pt:srcspan:krs:1.21:3",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "ca"
    },
    {
      "id": "pt:srcspan:krs:1.21:4",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.21:5",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.21:6",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "brahmadvāre"
    },
    {
      "id": "pt:srcspan:krs:1.21:7",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "sthite"
    },
    {
      "id": "pt:srcspan:krs:1.21:8",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "kāli"
    },
    {
      "id": "pt:srcspan:krs:1.21:9",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "vasturūpe"
    },
    {
      "id": "pt:srcspan:krs:1.21:10",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.21:11",
      "passage_id": "pt:passage:kramasadbhava:1.21",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.21:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.21:v1",
      "text": "\"[and]-O-stationed-in-the-midst-of-the-two-bows (kodaṇḍa-dvaya), [and]-at-the-drop's-end, homage-be-to-you; O-stationed-at-the-Brahmā's-door, O-Kālī, O-object-formed (vastu-rūpe), homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.21:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.21:1",
        "pt:srcspan:krs:1.21:2",
        "pt:srcspan:krs:1.21:3",
        "pt:srcspan:krs:1.21:4",
        "pt:srcspan:krs:1.21:5",
        "pt:srcspan:krs:1.21:6",
        "pt:srcspan:krs:1.21:7",
        "pt:srcspan:krs:1.21:8",
        "pt:srcspan:krs:1.21:9",
        "pt:srcspan:krs:1.21:10",
        "pt:srcspan:krs:1.21:11"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.21:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.21:v1"
  }
},
  "pt:passage:kramasadbhava:1.22": {
  "passage_id": "pt:passage:kramasadbhava:1.22",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-going-in-the-dissolution-sequence (saṃhāra-krama), always, O-creation-formed, homage-be-to-you; O-going-to-the-bulb-station (kanda-sthāna), always, O-called-the-coiled (kauṇḍalī), homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.22:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.22:1",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "saṃhārakramage"
    },
    {
      "id": "pt:srcspan:krs:1.22:2",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "nityaṃ"
    },
    {
      "id": "pt:srcspan:krs:1.22:3",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "sṛṣṭirūpe"
    },
    {
      "id": "pt:srcspan:krs:1.22:4",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "namastu"
    },
    {
      "id": "pt:srcspan:krs:1.22:5",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.22:6",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "kandasthānagate"
    },
    {
      "id": "pt:srcspan:krs:1.22:7",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "nityaṃ"
    },
    {
      "id": "pt:srcspan:krs:1.22:8",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "kauṇḍalyākhye"
    },
    {
      "id": "pt:srcspan:krs:1.22:9",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.22:10",
      "passage_id": "pt:passage:kramasadbhava:1.22",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.22:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.22:v1",
      "text": "\"[and]-O-going-in-the-dissolution-sequence (saṃhāra-krama), always, O-creation-formed, homage-be-to-you; O-going-to-the-bulb-station (kanda-sthāna), always, O-called-the-coiled (kauṇḍalī), homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.22:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.22:1",
        "pt:srcspan:krs:1.22:2",
        "pt:srcspan:krs:1.22:3",
        "pt:srcspan:krs:1.22:4",
        "pt:srcspan:krs:1.22:5",
        "pt:srcspan:krs:1.22:6",
        "pt:srcspan:krs:1.22:7",
        "pt:srcspan:krs:1.22:8",
        "pt:srcspan:krs:1.22:9",
        "pt:srcspan:krs:1.22:10"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.22:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.22:v1"
  }
},
  "pt:passage:kramasadbhava:1.23": {
  "passage_id": "pt:passage:kramasadbhava:1.23",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-stationed-in-the-...-the-...(*?) [X: \"matta-gandhaka-vāha\" — the rutting-elephant's-...?], O-apāna-formed, homage-be-to-you; O-the-six-cakras-devoid, O-Kālī, O-the-...-the-...(*?) [X: \"cakrānteśi\"], homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.23:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.23:1",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "mattagandhakavāhasthe'aapānarūpe"
    },
    {
      "id": "pt:srcspan:krs:1.23:2",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.23:3",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.23:4",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "ṣaṭcakravarjite"
    },
    {
      "id": "pt:srcspan:krs:1.23:5",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "kāli"
    },
    {
      "id": "pt:srcspan:krs:1.23:6",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "cakrānteśi"
    },
    {
      "id": "pt:srcspan:krs:1.23:7",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.23:8",
      "passage_id": "pt:passage:kramasadbhava:1.23",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.23:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.23:v1",
      "text": "\"[and]-O-stationed-in-the-...-the-...(*?) [X: \"matta-gandhaka-vāha\" — the rutting-elephant's-...?], O-apāna-formed, homage-be-to-you; O-the-six-cakras-devoid, O-Kālī, O-the-...-the-...(*?) [X: \"cakrānteśi\"], homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.23:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.23:1",
        "pt:srcspan:krs:1.23:2",
        "pt:srcspan:krs:1.23:3",
        "pt:srcspan:krs:1.23:4",
        "pt:srcspan:krs:1.23:5",
        "pt:srcspan:krs:1.23:6",
        "pt:srcspan:krs:1.23:7",
        "pt:srcspan:krs:1.23:8"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.23:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.23:v1"
  }
},
  "pt:passage:kramasadbhava:1.24": {
  "passage_id": "pt:passage:kramasadbhava:1.24",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-the-sixteen-supports-devoid (*?), [and]-O-in-the-support's-end, homage-be-to-you; O-in-the-three-lakhs-end (*?), O-stationed-in-the-mark-less, O-the-mark-less, homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.24:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.24:1",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "ṣoḍaśādhāranirmukte"
    },
    {
      "id": "pt:srcspan:krs:1.24:2",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "cādhārānte"
    },
    {
      "id": "pt:srcspan:krs:1.24:3",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.24:4",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.24:5",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "trilakṣānte"
    },
    {
      "id": "pt:srcspan:krs:1.24:6",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "alakṣasthe"
    },
    {
      "id": "pt:srcspan:krs:1.24:7",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "nirlakṣe"
    },
    {
      "id": "pt:srcspan:krs:1.24:8",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "ca"
    },
    {
      "id": "pt:srcspan:krs:1.24:9",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.24:10",
      "passage_id": "pt:passage:kramasadbhava:1.24",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.24:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.24:v1",
      "text": "\"[and]-O-the-sixteen-supports-devoid (*?), [and]-O-in-the-support's-end, homage-be-to-you; O-in-the-three-lakhs-end (*?), O-stationed-in-the-mark-less, O-the-mark-less, homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.24:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.24:1",
        "pt:srcspan:krs:1.24:2",
        "pt:srcspan:krs:1.24:3",
        "pt:srcspan:krs:1.24:4",
        "pt:srcspan:krs:1.24:5",
        "pt:srcspan:krs:1.24:6",
        "pt:srcspan:krs:1.24:7",
        "pt:srcspan:krs:1.24:8",
        "pt:srcspan:krs:1.24:9",
        "pt:srcspan:krs:1.24:10"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.24:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.24:v1"
  }
},
  "pt:passage:kramasadbhava:1.25": {
  "passage_id": "pt:passage:kramasadbhava:1.25",
  "work_id": "pt:work:kramasadbhava",
  "text": "\"[and]-O-beyond-the-fraction-of-the-sky-being (*?), O-unmanifest-mistress, homage-be-to-you; O-beyond-the-step-of-the-fragmented-form (*?), O-at-the-form's-end, homage-be-to-you:\"",
  "version_id": "pt:translation:kramasadbhava:1.25:v1",
  "version": 1,
  "source_spans": [
    {
      "id": "pt:srcspan:krs:1.25:1",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "vyomabhāvakalātīte"
    },
    {
      "id": "pt:srcspan:krs:1.25:2",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "avyakteśi"
    },
    {
      "id": "pt:srcspan:krs:1.25:3",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.25:4",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "te"
    },
    {
      "id": "pt:srcspan:krs:1.25:5",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "khaṇḍarūpapadātīte"
    },
    {
      "id": "pt:srcspan:krs:1.25:6",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "rūpānteśi"
    },
    {
      "id": "pt:srcspan:krs:1.25:7",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "namo'stu"
    },
    {
      "id": "pt:srcspan:krs:1.25:8",
      "passage_id": "pt:passage:kramasadbhava:1.25",
      "text": "te"
    }
  ],
  "target_spans": [
    {
      "id": "pt:tgtspan:krs:1.25:1",
      "translation_version_id": "pt:translation:kramasadbhava:1.25:v1",
      "text": "\"[and]-O-beyond-the-fraction-of-the-sky-being (*?), O-unmanifest-mistress, homage-be-to-you; O-beyond-the-step-of-the-fragmented-form (*?), O-at-the-form's-end, homage-be-to-you:\""
    }
  ],
  "alignments": [
    {
      "id": "pt:align:krs:1.25:1",
      "source_span_ids": [
        "pt:srcspan:krs:1.25:1",
        "pt:srcspan:krs:1.25:2",
        "pt:srcspan:krs:1.25:3",
        "pt:srcspan:krs:1.25:4",
        "pt:srcspan:krs:1.25:5",
        "pt:srcspan:krs:1.25:6",
        "pt:srcspan:krs:1.25:7",
        "pt:srcspan:krs:1.25:8"
      ],
      "target_span_ids": [
        "pt:tgtspan:krs:1.25:1"
      ],
      "type": "merged",
      "decision_ids": [],
      "method": "pipeline"
    }
  ],
  "decisions": [],
  "evidence": [],
  "review_state": "proposed",
  "provenance": {
    "base_source": "pt:src:kramasadbhava:dyczkowski-ed",
    "edition": "Dyczkowski ed., Muktabodha (NGMPP A 209/23)",
    "translation_version_id": "pt:translation:kramasadbhava:1.25:v1"
  }
},
};